### ISSUE TITLE
could you please give more  example image in the readme or your website about the document of this project

### ISSUE THREAD

**Issue by LanHuangJG** [WinUICommunity/WinUICommunity#1]
so that i could get more comfortable develop experence when use your library,and i think this project is  awesome .

**Comment by ghost1372** [comment]
Thank you
I will do this but for now i am a little busy, you can see demo app, or my personel projects such as Al-Anvar, TvTime and ArtWorks.
I use most of features in my projects

**Comment by SoyBeanMilkx** [comment]
is it based on wpf?or win32?

**Comment by ghost1372** [comment]
i updated docs (internally) with more images and i also updated Demo app and i will upload it in MS Store soon.
i am renaming WinUICommunity to WindowUI or Something else, so i am working on it and changes will be made public soon.

**Comment by ghost1372** [comment]
done
