### ISSUE TITLE
Using the HomeLandingPage in unpackaged app crashes

### ISSUE THREAD

**Issue by DFFspace** [WinUICommunity/WinUICommunity#14]
Hello, When I am publishing my app as unpackaged and starting it I notice it crashing straight away. If I take out the MainLandingPage or AllLandingPage and publish it the app works just fine. When I am taking out the HomeLandingPage or set a other page as default to start it works but I am than missing my sidebar items.

![image](https://github.com/WinUICommunity/WinUICommunity/assets/69241933/9ba1648c-bddf-48f5-b5da-0fb0d38c657e)

**Comment by DFFspace** [comment]
Here is the XAML code for the landingpage:

```xaml
<?xml version="1.0" encoding="utf-8" ?>
<Page
    x:Class="Example.App.Views.HomeLandingPage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:i="using:Microsoft.Xaml.Interactivity"
    xmlns:ic="using:Microsoft.Xaml.Interactions.Core"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    xmlns:wuc="using:WinUICommunity"
    mc:Ignorable="d">
    <wuc:MainLandingPage
        x:Name="allLandingPage"
        HeaderImage="{ThemeResource HeaderCover}"
        HeaderOverlayImage="{ThemeResource HeaderCover}"
        HeaderSubtitleText="v1.0.006"
        HeaderText="Example App">
        <i:Interaction.Behaviors>
            <ic:EventTriggerBehavior EventName="OnItemClick">
                <ic:EventTriggerBehavior.Actions>
                    <ic:InvokeCommandAction Command="{x:Bind ViewModel.ItemClickCommand}" />
                </ic:EventTriggerBehavior.Actions>
            </ic:EventTriggerBehavior>
        </i:Interaction.Behaviors>
        <wuc:MainLandingPage.HeaderContent>
            <StackPanel Orientation="Horizontal" Spacing="10">
                <wuc:HeaderTile
                    Title="Release Notes"
                    Description="Coming soon!"
                    Link="https://www.google.com">
                    <wuc:HeaderTile.Source>
                        <Image Source="/Assets/Fluent/light_bulb_3d.png" />
                    </wuc:HeaderTile.Source>
                </wuc:HeaderTile>
            </StackPanel>
        </wuc:MainLandingPage.HeaderContent>
    </wuc:MainLandingPage>
</Page>
```

Here the C# code:

```c#
namespace Example.App..Views;

public sealed partial class HomeLandingPage : Page
{
    public string AppInfo { get; set; }
    public HomeLandingViewModel ViewModel { get; }
    public HomeLandingPage()
    {
        ViewModel = App.GetService<HomeLandingViewModel>();
        InitializeComponent();
        AppInfo = $"{App.Current.AppName} v{App.Current.AppVersion}";
    }

    protected override void OnNavigatedTo(NavigationEventArgs e)
    {
        base.OnNavigatedTo(e);
        allLandingPage.GetData(ViewModel.JsonNavigationViewService.DataSource);
        allLandingPage.OrderBy(i => i.Title);
    }
}
```

**Comment by ghost1372** [comment]
did you add ItemTemplate in app.xaml?

```
<ResourceDictionary Source="ms-appx:///WinUICommunity.LandingPages/Themes/Generic.xaml" />
<wuc:ItemTemplates/>
```

**Comment by DFFspace** [comment]
Yes. The App has been created by using your WinUICommunityTemplates and than the WinUi 3 App - MVVM + NavigationView. Running the app through VS code or when going to the folder loc of the bin works just fine. It just fails to launch after its being published. 

Almost something similar with using the InfoBar (year or 2 ago) in a unpackaged app, where it crashed to while published to unpackaged.

**Comment by DFFspace** [comment]
Here is the sample project

https://github.com/DFFspace/App.CrashLandingPage

**Comment by ghost1372** [comment]
thank you i will test it.

**Comment by ghost1372** [comment]
@DFFspace 
It took me a long time to find the problem. But finally I found it and the answer was very simple.

The reason for this problem is that you are using .NET 8
That's why **WinUICommunity-Templates** Creates a .NET 8 compliant **RuntimeIdentifiers**
so if you use **Net 7** you have:
`<RuntimeIdentifiers>win10-x64</RuntimeIdentifiers>
`
and if you use **Net 8** you have:
`<RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
`
**Unfortunately, WinUI 3 does not support .NET 8 well.**

That's why we have to have the **RuntimeIdentifiers** in the **PublishProfiles** file as follows:
`<RuntimeIdentifier>win10-x64</RuntimeIdentifier>
`
I already fixed this problem to create the correct RuntimeIdentifiers.
So I guess you are using old VSIX (WinUICommunity-Templates) and haven't updated yet.

To fix this issue, just edit the **RuntimeIdentifiers** in **PublishProfiles** to `win10-x64`:

![Screenshot 2023-12-21 191710](https://github.com/WinUICommunity/WinUICommunity/assets/9213496/739fb0b3-f990-4712-85e5-96a1cb13a4c1)
![xxx](https://github.com/WinUICommunity/WinUICommunity/assets/9213496/02757480-c48f-4b79-92c2-40e44d8294aa)

**Comment by DFFspace** [comment]
Thanks for your reply! I've checked and after changing the RuntimeIdentifier, it does work. Thank you! The WinUICommunity Template for WinUI is on version 4.5.0. I did notice that if I open the Publish section and make an edit, it will revert back to win-x64. After testing with your template studio, it sets the Runtime correctly, but after making an edit and clicking ok, it seems to revert back.



https://github.com/WinUICommunity/WinUICommunity/assets/69241933/e42de002-5370-45f2-8a4f-12b3a6d24510

**Comment by ghost1372** [comment]
@DFFspace  thank you for confirmation.
Yes, changing Runtime will be revert.
you should edit runtime from pubxml file and not vs wizard. after that you can use vs wizard but dont touch runtime option.
this is vs bug and i will report to vs dev team if i have enough time.
