### ISSUE TITLE
Cannot change shortcut

### ISSUE THREAD

**Issue by insomniachi** [WinUICommunity/WinUICommunity#15]
![image](https://github.com/WinUICommunity/WinUICommunity/assets/6525704/a873ebfb-6ded-4165-b15f-491a3d02ce61)
pressing buttons doesn't change anything, this is from the demo app.
looking at the code there is nothing written to update, even though the UI says it can.

**Comment by ghost1372** [comment]
This is just a UI control without logic, so you have to write your logic, logic code was in c++ so i did not port it.
