### ISSUE TITLE
Cannot add package into class library project

### ISSUE THREAD

**Issue by book1625** [WinUICommunity/WinUICommunity#16]
Step 1 :  create class library for winui project (.net 6 or 8) via VS2022 project template

![螢幕擷取畫面 2023-12-28 141202](https://github.com/WinUICommunity/WinUICommunity/assets/26806819/cd5d1d57-2a98-4cb4-b4cb-b884748d6013)

Step 2 :  update all nuget packages
Step 3 :  add WinUICommunity.Core into this project

![螢幕擷取畫面 2023-12-28 141254](https://github.com/WinUICommunity/WinUICommunity/assets/26806819/d9088348-612f-41c6-9aad-d848765642f9)

Step 4 :  build and compile failed

![螢幕擷取畫面 2023-12-28 141321](https://github.com/WinUICommunity/WinUICommunity/assets/26806819/01c4825b-14c7-4db8-93a5-a2e57ed521dc)

if we change the step1 , create a winui app project instead of class library for winui project, it work well ~

**Comment by ghost1372** [comment]
thank you, i will fix this issue
