### ISSUE TITLE
Feature: Add quick view of the usage code

### ISSUE THREAD

**Issue by JeremyWu917** [WinUICommunity/WinUICommunity#18]
Hi
It's cool repo for wpfer ☕ 
Do you have any plans to add a quick view of the usage code?

And looks like below screenshots, thanks so much.
![image](https://github.com/WinUICommunity/WinUICommunity/assets/54832272/3492225d-931c-4f0b-9387-1e37dfbf3d38)

**Comment by ghost1372** [comment]
Hi @JeremyWu917  thank you for your suggestion.

I have already ported the OptionsPageControl from winui-gallery repo.
So, adding a Example code to its footer is not difficult. 
I am a bit busy but I will do it soon.
Also i want to publish sample to MS Store 😄

**Comment by JeremyWu917** [comment]
> Hi @JeremyWu917 thank you for your suggestion.
> 
> I have already ported the OptionsPageControl from winui-gallery repo. So, adding a Example code to its footer is not difficult. I am a bit busy but I will do it soon. Also i want to publish sample to MS Store 😄

Great job and after that I believe this repo will be more and more popular 🚀

**Comment by ghost1372** [comment]
Hi @JeremyWu917 Thank you🙏❤️
I completely ported the source code controls, and DemoApp is ready for new ExampleControl + Source Code!
Whenever I get enough time, I will update the DemoApp with this new ExampleControl 
You can see an example here:

![3](https://github.com/WinUICommunity/WinUICommunity/assets/9213496/5e2e3cd3-c8ac-4156-83f3-398165b5a7b0)

**Comment by ghost1372** [comment]
another demo
![image](https://github.com/WinUICommunity/WinUICommunity/assets/9213496/5d0ecb63-b353-4583-89b8-c0d63bcd22d1)

**Comment by ghost1372** [comment]
90% Samples Updated with New Template, I will do the rest in the coming days. now we can Go to Doc (Click on Document Icon) and we can see Xaml/CSharp Codes
Final Result:

![image](https://github.com/WinUICommunity/WinUICommunity/assets/9213496/a18c58c6-c7b0-4327-a7bc-405c2d932733)

**Comment by ghost1372** [comment]
@JeremyWu917 Microsoft Store Version Now is Available 🔥🚀
https://apps.microsoft.com/detail/WUC%20Gallery%20App/9mswnv3wmqc1?launch=true&mode=mini

**Comment by JeremyWu917** [comment]
Good job bro👍



Sent&nbsp;from&nbsp;my&nbsp;iPhone


------------------ Original ------------------
From: Mahdi Hosseini ***@***.***&gt;
Date: Wed,Apr 17,2024 9:19 PM
To: WinUICommunity/WinUICommunity ***@***.***&gt;
Cc: Jeremy Wu ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [WinUICommunity/WinUICommunity] Feature: Add quick view of theusage code (Issue #18)





 
@JeremyWu917 Microsoft Store Version Now is Available 🔥🚀
 https://apps.microsoft.com/detail/WUC%20Gallery%20App/9mswnv3wmqc1?launch=true&amp;mode=mini
