### ISSUE TITLE
[SUGGESTION]  Rename services and helpers. 

### ISSUE THREAD

**Issue by Petrarca181** [WinUICommunity/WinUICommunity#19]
I've been using the official WinUI templates to set up navigation + your winui core features. However, I've been running into some issues with namespace references, especially when it comes to navigation elements like INavigationService, INavigationAware, PageService, etc.

I'm aware that these issues can be resolved with proper usings and External Aliases, but it seems a bit cumbersome.

**Comment by ghost1372** [comment]
Thanks for the suggestion
I will try to fix this issue in the next version (mybe we should use INavigationServiceEx or something else... I don't want to make major changes)
