### ISSUE TITLE
[SUGGESTION] TitleBar  Improvements

### ISSUE THREAD

**Issue by Petrarca181** [WinUICommunity/WinUICommunity#20]
The caption buttons do not respond to theme changes unless we utilize WinuiCommunity.Titlebar as the title bar. Is it feasible to segregate these two features so that the ThemeService manages all color modifications? Additionally, I would like to add width and margin properties to the Back/Toggle button. For instance, my NavView's CompactPaneLength is set to 60, but the back button appears too small and doesn't look good. I am currently addressing this issue by overriding the style. Here's an example:

```
<winuicommunity:TitleBar.Resources>
   <Style x:Key="TitleBarBackButtonStyle" TargetType="Button">
       <Setter Property="Width" Value="60" />
       ...................................................................................
   </Style>
</winuicommunity:TitleBar.Resources>
```

Thank you.

**Comment by ghost1372** [comment]
Hi @Petrarca181 
If I remember correctly I removed the theme change response feature when I added the title bar. I will check again.
i will add some properties for Titlebar so we can handle this situations.

I am currently adding some Win2d controls (today i am adding Demos you can give it a try), it may take a few days.

**Comment by ghost1372** [comment]
> > Hi @Petrarca181 If I remember correctly I removed the theme change response feature when I added the title bar. I will check again. i will add some properties for Titlebar so we can handle this situations.
> > I am currently adding some Win2d controls (today i am adding Demos you can give it a try), it may take a few days.
> 
> Thank you. There is nothig critical take your time. I'm on last version and untill I feed AppTitleBar.Window = App.MainWindow; caption buttons foreground will be always white.
> 
> Offtopic: Do you know what they changed in win2d after 1.0.5.0 version? I have some lottie files generated with lottiegen and they reference Canvas. Recent win2d update just break all those files.

I haven't used the previous versions much and I don't know. but for version 1.1.1 we need to update TargetFrameworks to 22621 so I guess there have been many and fundamental changes

**Comment by ghost1372** [comment]
@Petrarca181  I added Some Properties for Margin and Width.
today i tested a Blank WinUI 3 + without any WinUICommunity packages/Titlebar
i just added 
`ExtendsContentIntoTitleBar = true;`
and Caption Buttons background works perfeclty!
I don't think we need to fix this in our ThemeService.
also there is a open [pr](https://github.com/microsoft/WindowsAppSDK/pull/4035) in wasdk repo which provides this possibility by default.
