### ISSUE TITLE
6.1.0 Has some problems

### ISSUE THREAD

**Issue by Petrarca181** [WinUICommunity/WinUICommunity#21]
Hi, it's me again. 

**Published Demo app is broken:**
<details>
  <summary>Spoiler</summary>
  
![DEMO APP](https://github.com/WinUICommunity/WinUICommunity/assets/54235138/97a75555-04ab-4298-b947-f5e99c782462)

 </details>

**Theme service makes my app crash:**

```
var themeService = App.GetService<IThemeService>();
themeService.Initialize(App.MainWindow, false);
themeService.ConfigElementTheme(ElementTheme.Default);
themeService.ConfigBackdrop(BackdropType.Mica);
```

App will start as usual and works fine. I my settings page I don't register combo box but use my methods where I try to set theme like this:
```
var theme = ThemeIndex switch
{
    0 => ElementTheme.Light,
    1 => ElementTheme.Dark,
   _ => ElementTheme.Default
};

if (theme == _themeService.GetElementTheme())
    return;

_themeService.SetElementTheme(theme);
```
using `_themeService.SetElementTheme(theme);` will lead to app crash

<details>
  <summary>Exception</summary>
  
```
Parameter is not correct.
target
```

Stack trace:
```
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Microsoft.UI.Xaml.Media.ISystemBackdropOverridesMethods.OnDefaultSystemBackdropConfigurationChanged(IObjectReference _obj, ICompositionSupportsSystemBackdrop target, XamlRoot xamlRoot)
   at Microsoft.UI.Xaml.Media.SystemBackdrop.OnDefaultSystemBackdropConfigurationChanged(ICompositionSupportsSystemBackdrop target, XamlRoot xamlRoot)
   at Microsoft.UI.Xaml.Media.SystemBackdrop.Microsoft.UI.Xaml.Media.ISystemBackdropOverrides.OnDefaultSystemBackdropConfigurationChanged(ICompositionSupportsSystemBackdrop target, XamlRoot xamlRoot)
   at ABI.Microsoft.UI.Xaml.Media.ISystemBackdropOverrides.Do_Abi_OnDefaultSystemBackdropConfigurationChanged_2(IntPtr thisPtr, IntPtr target, IntPtr xamlRoot)

```
 </details>

I found if configuting/setting first time to Backdroptype to None and after set it to mica or other changing theme will  work fine. 

**I still have question about titlebar buttons.  Yes changing theme in windows will work fine.** 
<details>
  <summary>Spoiler </summary>

  
![AUTO THEME](https://github.com/WinUICommunity/WinUICommunity/assets/54235138/ca5cb28b-cbbf-43f5-af60-ab0e6084d8f8)

</details>

But changing theme via Themeservice will not change button foreground till I use your titlebar + `AppTitleBar.Window = App.MainWindow;`

<details>
  <summary>Spoiler</summary>

![kek](https://github.com/WinUICommunity/WinUICommunity/assets/54235138/66fac2b3-b311-4a97-ae6a-452c264e2e18)

</details>

Is this intended to work like this?

**Comment by ghost1372** [comment]
Hi, yes, unfortunately, I noticed the problem after publishing.
I am working on a fix and i will release a new version soon. I'm sorry about that.

**Comment by ghost1372** [comment]
> ActualThemeChnaged event manually.

can you explain more? there is already a ActualThemeChnaged event and you can add it.
`ThemeService.ActualThemeChanged += ThemeChanged;`

**Comment by ghost1372** [comment]
> > > ActualThemeChnaged event manually.
> > 
> > 
> > can you explain more? there is already a ActualThemeChnaged event and you can add it. `ThemeService.ActualThemeChanged += ThemeChanged;`
> 
> I'm just stupitd. I forgot to delete My ThemeService. This why I wasn't able to find ActualThemeChanged :).

😅
i am uploading version 6.2.0 (will be available in a 30 minutes) and this version can fix ThemeService Backdrop issue, however TintColor Feature will be disabled until i fix Backdrop TintColor (i think this may take a little more time). so i am closing this issue

**Comment by ghost1372** [comment]
@Petrarca181 
wait for **6.3.0**  (6.2.0 is buggy🤬) The problems are observed right after uploading the new version. Oh God, this is madness
