### ISSUE TITLE
Reg... Dark Theme.

### ISSUE THREAD

**Issue by kannanrs** [WinUICommunity/WinUICommunity#23]
Switching to dark theme, displays in light gray than black... Have i missed something... the version im using is .net7 and the template..

TIA

**Comment by ghost1372** [comment]
I think you dont use a backdrop or background, so please set a backdrop like mica or acrylic for your window or set a background for your page.

**Comment by kannanrs** [comment]
is this in the samples please... did some changes to the background or somewhere and get a graysmoke kind when i turn on the dark mode

**Comment by ghost1372** [comment]
Yes you can use our Demo project to see how its work.
Can you upload a sample repro project?

**Comment by kannanrs** [comment]
![image_2024-02-22_160214182](https://github.com/WinUICommunity/WinUICommunity/assets/7222865/3b606a92-a455-430b-a5ba-5b9613afc835)

**Comment by kannanrs** [comment]
got it... thank you very much...
