### ISSUE TITLE
The SystemBackdrop of the window will turn solid black if it is none, and will not respond to theme changes

### ISSUE THREAD

**Issue by scx1125** [WinUICommunity/WinUICommunity#25]
The SystemBackdrop of the window will turn solid black if it is none, and will not respond to theme changes
![image](https://github.com/WinUICommunity/WinUICommunity/assets/34766580/191d24ea-6b8b-4e65-8553-0b237dc27bc3)

**Comment by ghost1372** [comment]
this is normal!
if you want to use Backdrop (no matter it is None or Mica or Acrylic...) you should remove any background from your page or window. that theme changes does not work as expected!

If you want theme changes to work well, you should consider a background for your window or page.
