### ISSUE TITLE
[Bug] NavigationService -Footer navigation doesn't work

### ISSUE THREAD

**Issue by RolandBuchholz** [WinUICommunity/WinUICommunity#27]
It is not possible to navigate to a FooterNavigationViewItem. 
The problem is that JsonNavigationViewService only returns the MenuItems, 
the FooterMenuItems are not returned. 
`IList<object>? MenuItems => _navigationView?.MenuItems;`
This means that only the MenuItems are configured in ConfigPages.
```
    private void ConfigPages()
    {
        _pageService.GetPages(MenuItems);
```
It would be conceivable to also integrate the FooterItems into ConfigPages.
Either the `IList<object>? MenuItems` also contains the FooterItems, 
or an additional `IList<object>? FooterMenuItems` which is then processed by the ConfigPages.

**Comment by ghost1372** [comment]
Thanks @RolandBuchholz 
Fixed
