### ISSUE TITLE
Buttons are not clickable

### ISSUE THREAD

**Issue by Alloyd031** [WinUICommunity/WinUICommunity#29]
![image](https://github.com/WinUICommunity/WinUICommunity/assets/71263641/e49e3e07-88fb-4116-adcf-233292eb090c)

I tried to out them into TitleBar.Content, but they are still not clickable. Correct me if i'm wrong.

**Comment by ghost1372** [comment]
Please send me a sample project, also we will remove titlebar control when wasdk v1.6 released. A new titlebar control just like this will be added into wasdk v1.6

**Comment by Alloyd031** [comment]
Sorry i deleted it by mistake. Will remake it soon.
