### ISSUE TITLE
i want a demo app to know the real experence but i get 404

### ISSUE THREAD

**Issue by LanHuangJG** [WinUICommunity/WinUICommunity#3]
<img width="1280" alt="image" src="https://github.com/WinUICommunity/WinUICommunity/assets/125177842/8e78f121-b6fe-4442-bfb2-37a1e24521b3">

**Comment by ghost1372** [comment]
Tnx for report some url is wrong in docs website i will fix them soon. Also you can send my wrong pages and i can do this fast.
Until i fix wrong links you can use:
Download demo app from release
https://github.com/WinUICommunity/WinUICommunity/releases

Or explore source code
https://github.com/WinUICommunity/WinUICommunity/tree/main/Samples

**Comment by ghost1372** [comment]
done
