### ISSUE TITLE
Question: How to get rid of black 1px borders on Windows 10 without using WinUICommunity template?

### ISSUE THREAD

**Issue by Alloyd031** [WinUICommunity/WinUICommunity#32]

**Comment by ghost1372** [comment]
I need more info, i cant understand your issue

**Comment by Alloyd031** [comment]
![Image](https://github.com/user-attachments/assets/cc031851-7e6c-4fdc-8413-8def7ce6469b)
I'm talking about this.

**Comment by ghost1372** [comment]
Hmm... i think mybe this is caused by TitleBar control.  We will remove it when wasdk v1.6 released. You can try to remove titlebar and test it. Also i think you can try to use appwindow and
`SetBorderAndTitleBar`

**Comment by Alloyd031** [comment]
Does DwmExtendFrameIntoClientArea from your source code help?

**Comment by ghost1372** [comment]
I dont know you should test it. i dont have win10 for test it.
