### ISSUE TITLE
Bug: Cannot drag the titlebar after setting ExtendsContentIntoTitleBar=true

### ISSUE THREAD

**Issue by Alloyd031** [WinUICommunity/WinUICommunity#33]

**Comment by ghost1372** [comment]
make sure you are using titlebar in correct way, also titlebar height option not supported and you can control height with overriding this keys:

```
<x:Double x:Key="TitleBarCompactHeight">32</x:Double>
    <x:Double x:Key="TitleBarTallHeight">48</x:Double>
```

https://ghost1372.github.io/winUICommunityComponents/controls/titleBar/

**Comment by ghost1372** [comment]
titlebar control removed
