### ISSUE TITLE
i found a bug with your titlebar

### ISSUE THREAD

**Issue by LanHuangJG** [WinUICommunity/WinUICommunity#4]
![image](https://github.com/WinUICommunity/WinUICommunity/assets/125177842/31b321ba-561c-4f5e-9093-42cd4700ff6f)
# this is my code
when i select the light the icon is black
instead is white ,but when i select light to use system setting,the icon color is not change,
but select from dark to use system setting the codition is normal

https://github.com/WinUICommunity/WinUICommunity/assets/125177842/d34aa112-a994-4fba-a26d-b6f3b6d42b08

**Comment by ghost1372** [comment]
Hi @LanHuangJG 
titlebar does not handle background colors. you can do this your self like this:
`currentWindow.AppWindow.TitleBar.ButtonBackgroundColor = Colors.Transparent;`

also if you use WinUICommunity.Core package, you can use ThemeService which will handle everything.


https://github.com/WinUICommunity/WinUICommunity/assets/9213496/a64aa0b6-f931-4853-90ac-2f0014c0acf4
