### ISSUE TITLE
Breadcrumb Navigation

### ISSUE THREAD

**Issue by RoccoZero** [WinUICommunity/WinUICommunity#40]
Сan you add an easy way to Breadcrumb Navigation?
I think it looks very convenient
Of course it needs some improvement

https://github.com/Jurij15/WinUI3BreadcrumbNavigationSample/tree/master
https://streamable.com/xnzmzh

**Comment by ghost1372** [comment]
If you have used https://[github.com/winUICommunity/WinUICommunity-Templates](https://github.com/winUICommunity/WinUICommunity-Templates), we have used a breadcrumb control for settings page

![BreadcrumbNavigator](https://github.com/user-attachments/assets/8e9bd4fe-d2de-44d3-8d05-8ce7fd873947)

I refactored it a bit yesterday to make it easier to use
https://github.com/WinUICommunity/WinUICommunity/blob/main/dev/Components/Controls/Navigator/BreadcrumbNavigator.xaml

I will check your links and if I find something useful, I will definitely add it to the components library.

**Comment by ghost1372** [comment]
Done
