### ISSUE TITLE
PinBox not presented

### ISSUE THREAD

**Issue by aexra** [WinUICommunity/WinUICommunity#41]
Cannot find PinBox from README at all neither in WUC package nor WUC Gallery App. I missed something?

**Comment by ghost1372** [comment]
are you using latest v7.0.0-Preview version? or you are using 6.9.0 stable release? PinBox included in v7.0.0-preview and not available in 6.9.0

![image](https://github.com/user-attachments/assets/ab239381-ef65-4389-8579-ad112809196a)

**Comment by aexra** [comment]
Got it, thanks
However, I created project with your Template Studio (or how it calls) and changing WinUICommunity to v7.0.0-preview causes `Nucs` namespace to disappear so many other things wont work. Any ideas or I just wait for 7.0.0 template release?

**Comment by ghost1372** [comment]
> Got it, thanks
> However, I created project with your Template Studio (or how it calls) and changing WinUICommunity to v7.0.0-preview causes `Nucs` namespace to disappear so many other things wont work. Any ideas or I just wait for 7.0.0 template release? 

There are some breaking changes because of Native AOT, wait for template new version or you can compile it yourself
