### ISSUE TITLE
"ContextMenuService" does not include a definition for "Ins".

### ISSUE THREAD

**Issue by lostluna1** [WinUICommunity/WinUICommunity#42]
When creating a project using the WinUICommunity template, the OnLaunched method is:

protected async override void OnLaunched(LaunchActivatedEventArgs args)
{
    CurrentWindow = new Window();

    CurrentWindow.AppWindow.TitleBar.ExtendsContentIntoTitleBar = true;
    CurrentWindow.AppWindow.TitleBar.ButtonBackgroundColor = Colors.Transparent;

    if (CurrentWindow.Content is not Frame rootFrame)
    {
        CurrentWindow.Content = rootFrame = new Frame();
    }

    rootFrame.Navigate(typeof(MainPage));

    CurrentWindow.Title = CurrentWindow.AppWindow.Title = $"{AppName} v{AppVersion}";
    CurrentWindow.AppWindow.SetIcon("Assets/icon.ico");

    CurrentWindow.Activate();
    ContextMenuItem menu = new ContextMenuItem
    {
        Title = "Open App1 Here",
        AcceptDirectory = true,
        Exe = "App1.exe",
        Param = "{path}"
    };
    await ContextMenuService.Ins.SaveAsync(menu);
    await DynamicLocalizerHelper.InitializeLocalizer("en-US");
}

**Comment by lostluna1** [comment]
Is it caused by a different version being released?

**Comment by ghost1372** [comment]
@lostluna1 
Use this way:
```
ContextMenuService menuService = new ContextMenuService();
await menuService.SaveAsync(menu);
```

please see our docs:
https://ghost1372.github.io/winUICommunityContextMenuExtensions/

**Comment by lostluna1** [comment]
> 使用这种方式：
> 
> ```
> ContextMenuService menuService = new ContextMenuService();
> await menuService.SaveAsync(menu);
> ```
> 
> 请参阅我们的文档：https://ghost1372.github.io/winUICommunityContextMenuExtensions/
> 
> 新版本 （v7.0.0） 即将推出，并且 Docs 页面将更新新的详细信息。因此，请使用 NuGet 中提供的最新预览版。此版本将很快稳定。

thanks!!
