### ISSUE TITLE
Was 7.0.0 final removed from Nuget for any particular reason?

### ISSUE THREAD

**Issue by MPITech** [WinUICommunity/WinUICommunity#48]
I am only seeing 7.0.0-preview4 in VS 2022 Nuget now.  I wanted to give 7.0.0 final another try.  Thanks again.

**Comment by ghost1372** [comment]
V7.0.0 is based on wasdk v.1.6.2 and ms unlisted v1.6.2 from nuget due to a critical bug on windows 10. We also had to unlist version 7.0.0 until the new wasdk version is released .
Fortunately, the problem has been identified and a new version will be released soon.

**Comment by MPITech** [comment]
Thanks!
