### ISSUE TITLE
[BUG] Drag regions in the TitleBar control calculated Incorrectly

### ISSUE THREAD

**Issue by dzhukovsky** [WinUICommunity/WinUICommunity#9]
For clarity, I added a minimum width and color for each TitleBar element:

![image](https://github.com/WinUICommunity/WinUICommunity/assets/136100876/491460e4-6954-4634-8408-241039fdf7e0)

Тhis is what it looks like:

![image](https://github.com/WinUICommunity/WinUICommunity/assets/136100876/b2c8a9d3-8bc1-41e9-8ca5-fcca18b36bb2)

### Problem 1
`PART_RootGrid` has `Padding.Right` causing the window button area to move to the right:
![image](https://github.com/WinUICommunity/WinUICommunity/assets/136100876/f3115b09-04a6-4b95-b843-7b60083b424a)

#### Fix
Set `Padding="4,0,0,0"` for `PART_RootGrid`:
https://github.com/WinUICommunity/WinUICommunity/blob/b959f0342c129db75d0370ac42c7f9ccf5c1bf5e/dev/Components/Controls/Labs/TitleBar/TitleBar.xaml#L21C33-L21C33

### Problem 2
Due to `PART_RootGrid.Padding.Left` regions are calculated incorrectly:
https://github.com/WinUICommunity/WinUICommunity/assets/136100876/148de3cd-9a70-49b5-a87a-a6f4ca2331e2

#### Fix
Fix SetDragRegionForCustomTitleBar method.
Plus (+) is draggable area, minus (-) is non-draggable area.
```
+[rootGrid.padding.left][leftPadding]
-[buttonsHolder]
+[icon][title][leftDrag]
-[content]
+[rightDrag]
-[footer]
+[rightPadding][rootGrid.padding.right]            
```

I after applying fix, it will look like this:
https://github.com/WinUICommunity/WinUICommunity/assets/136100876/4637e586-82a4-4266-9553-ee1566b238b3

```cs
private void SetDragRegionForCustomTitleBar()
{
    if (AutoConfigureCustomTitleBar && Window != null && PART_RightPaddingColumn != null && PART_LeftPaddingColumn != null)
    {
        double scaleAdjustment = GetScaleAdjustment();

        PART_RightPaddingColumn.Width = new GridLength(Window.AppWindow.TitleBar.RightInset / scaleAdjustment);
        PART_LeftPaddingColumn.Width = new GridLength(Window.AppWindow.TitleBar.LeftInset / scaleAdjustment);

        var height = (int)(this.ActualHeight * scaleAdjustment);
        Windows.Graphics.RectInt32 rect1 = new(0, 0, 0, height);
        Windows.Graphics.RectInt32 rect2 = new(0, 0, 0, height);
        Windows.Graphics.RectInt32 rect3 = new(0, 0, 0, height);
        Windows.Graphics.RectInt32 rect4 = new(0, 0, 0, height);

        rect1.X = 0;
        rect1.Width = (int)((PART_RootGrid.Padding.Left
                            + PART_LeftPaddingColumn.ActualWidth)
                            * scaleAdjustment);

        rect2.X = rect1.X + rect1.Width + (int)((PART_ButtonsHolderColumn.ActualWidth) * scaleAdjustment);
        rect2.Width = (int)((PART_IconColumn.ActualWidth
                            + PART_TitleColumn.ActualWidth
                            + PART_LeftDragColumn.ActualWidth)
                            * scaleAdjustment);

        rect3.X = rect2.X + rect2.Width + (int)(PART_ContentColumn.ActualWidth * scaleAdjustment);
        rect3.Width = (int)(PART_RightDragColumn.ActualWidth * scaleAdjustment);

        rect4.X = rect3.X + rect3.Width + (int)((PART_FooterColumn.ActualWidth
                                                + PART_RightPaddingColumn.ActualWidth
                                                + PART_RootGrid.Padding.Right)
                                                * scaleAdjustment);
        rect4.Width = (int)(PART_RightPaddingColumn.ActualWidth * scaleAdjustment);

        Windows.Graphics.RectInt32[] dragRects = new[] { rect1, rect2, rect3, rect4 };
        Window.AppWindow.TitleBar.SetDragRectangles(dragRects);
    }
}
```

### Patch

```patch
Author: Dmitry Zhukovsky <136100876+dzhukovsky@users.noreply.github.com>  2023-11-04 17:51:03
Committer: Dmitry Zhukovsky <136100876+dzhukovsky@users.noreply.github.com>  2023-11-04 17:51:03
Parent: b959f0342c129db75d0370ac42c7f9ccf5c1bf5e (Fix #8 Tnx to @dzhukovsky)
Branch: main
Follows: v5.3.1
Precedes: 

    Fix drag regions calculation in the TitleBar control.

----------- dev/Components/Controls/Labs/TitleBar/TitleBar.WASDK.cs -----------
index 3d16fe6..b9b628a 100644
@@ -17,6 +17,7 @@ namespace WinUICommunity;
 [TemplatePart(Name = nameof(PART_FooterColumn), Type = typeof(ColumnDefinition))]
 [TemplatePart(Name = nameof(PART_RightDragColumn), Type = typeof(ColumnDefinition))]
 [TemplatePart(Name = nameof(PART_TitleHolder), Type = typeof(StackPanel))]
+[TemplatePart(Name = nameof(PART_RootGrid), Type = typeof(Grid))]
 
 public partial class TitleBar : Control
 {
@@ -28,6 +29,7 @@ public partial class TitleBar : Control
     ColumnDefinition? PART_FooterColumn;
     ColumnDefinition? PART_RightDragColumn;
     StackPanel? PART_TitleHolder;
+    Grid? PART_RootGrid;
 
     private void SetWASDKTitleBar()
     {
@@ -41,7 +43,7 @@ public partial class TitleBar : Control
             Window.AppWindow.TitleBar.ExtendsContentIntoTitleBar = true;
 
             ConfigPresenter();
-            
+
             this.Window.Activated -= Window_Activated;
             this.Window.Activated += Window_Activated;
 
@@ -63,6 +65,7 @@ public partial class TitleBar : Control
             PART_RightDragColumn = GetTemplateChild(nameof(PART_RightDragColumn)) as ColumnDefinition;
             PART_FooterColumn = GetTemplateChild(nameof(PART_FooterColumn)) as ColumnDefinition;
             PART_TitleHolder = GetTemplateChild(nameof(PART_TitleHolder)) as StackPanel;
+            PART_RootGrid = GetTemplateChild(nameof(PART_RootGrid)) as Grid;
 
             // Get caption button occlusion information.
             int CaptionButtonOcclusionWidthRight = Window.AppWindow.TitleBar.RightInset;
@@ -137,35 +140,33 @@ public partial class TitleBar : Control
             PART_RightPaddingColumn.Width = new GridLength(Window.AppWindow.TitleBar.RightInset / scaleAdjustment);
             PART_LeftPaddingColumn.Width = new GridLength(Window.AppWindow.TitleBar.LeftInset / scaleAdjustment);
 
-            List<Windows.Graphics.RectInt32> dragRectsList = new();
-
-            Windows.Graphics.RectInt32 dragRectL;
-            dragRectL.X = (int)((PART_LeftPaddingColumn.ActualWidth
-                            + PART_ButtonsHolderColumn!.ActualWidth)
-                            * scaleAdjustment);
-            dragRectL.Y = 0;
-            dragRectL.Height = (int)(this.ActualHeight * scaleAdjustment);
-            dragRectL.Width = (int)((PART_IconColumn!.ActualWidth
-                                + PART_TitleColumn!.ActualWidth
-                                + PART_LeftDragColumn!.ActualWidth)
+            var height = (int)(this.ActualHeight * scaleAdjustment);
+            Windows.Graphics.RectInt32 rect1 = new(0, 0, 0, height);
+            Windows.Graphics.RectInt32 rect2 = new(0, 0, 0, height);
+            Windows.Graphics.RectInt32 rect3 = new(0, 0, 0, height);
+            Windows.Graphics.RectInt32 rect4 = new(0, 0, 0, height);
+
+            rect1.X = 0;
+            rect1.Width = (int)((PART_RootGrid.Padding.Left
+                                + PART_LeftPaddingColumn.ActualWidth)
                                 * scaleAdjustment);
-            dragRectsList.Add(dragRectL);
-
-            Windows.Graphics.RectInt32 dragRectR;
-            dragRectR.X = (int)((PART_LeftPaddingColumn.ActualWidth
-                                + PART_IconColumn.ActualWidth
-                                + PART_ButtonsHolderColumn!.ActualWidth
-                                + PART_TitleHolder!.ActualWidth
-                                + PART_LeftDragColumn.ActualWidth
-                                + PART_ContentColumn!.ActualWidth)
+
+            rect2.X = rect1.X + rect1.Width + (int)((PART_ButtonsHolderColumn.ActualWidth) * scaleAdjustment);
+            rect2.Width = (int)((PART_IconColumn.ActualWidth
+                                + PART_TitleColumn.ActualWidth
+                                + PART_LeftDragColumn.ActualWidth)
                                 * scaleAdjustment);
-            dragRectR.Y = 0;
-            dragRectR.Height = (int)(this.ActualHeight * scaleAdjustment);
-            dragRectR.Width = (int)(PART_RightDragColumn!.ActualWidth * scaleAdjustment);
-            dragRectsList.Add(dragRectR);
 
-            Windows.Graphics.RectInt32[] dragRects = dragRectsList.ToArray();
+            rect3.X = rect2.X + rect2.Width + (int)(PART_ContentColumn.ActualWidth * scaleAdjustment);
+            rect3.Width = (int)(PART_RightDragColumn.ActualWidth * scaleAdjustment);
+
+            rect4.X = rect3.X + rect3.Width + (int)((PART_FooterColumn.ActualWidth
+                                                    + PART_RightPaddingColumn.ActualWidth
+                                                    + PART_RootGrid.Padding.Right)
+                                                    * scaleAdjustment);
+            rect4.Width = (int)(PART_RightPaddingColumn.ActualWidth * scaleAdjustment);
 
+            Windows.Graphics.RectInt32[] dragRects = new[] { rect1, rect2, rect3, rect4 };
             Window.AppWindow.TitleBar.SetDragRectangles(dragRects);
         }
     }

------------- dev/Components/Controls/Labs/TitleBar/TitleBar.xaml -------------
index 61e01c5..983dad2 100644
@@ -18,7 +18,7 @@
                 <ControlTemplate TargetType="local:TitleBar">
                     <Grid x:Name="PART_RootGrid"
                           Height="{TemplateBinding MinHeight}"
-                          Padding="4,0,4,0"
+                          Padding="4,0,0,0"
                           VerticalAlignment="Stretch"
                           Background="{TemplateBinding Background}">
                         <Grid.ColumnDefinitions>

---------------------- dev/Components/Themes/Generic.xaml ----------------------
index 877fb1e..ae49b15 100644
@@ -2090,7 +2090,7 @@ Themes\Styles\TextBlock.xaml
     <win:Setter Property="Template">
       <win:Setter.Value>
         <win:ControlTemplate TargetType="local:TitleBar">
-          <win:Grid x:Name="PART_RootGrid" Height="{TemplateBinding MinHeight}" Padding="4,0,4,0" VerticalAlignment="Stretch" Background="{TemplateBinding Background}">
+          <win:Grid x:Name="PART_RootGrid" Height="{TemplateBinding MinHeight}" Padding="4,0,0,0" VerticalAlignment="Stretch" Background="{TemplateBinding Background}">
             <win:Grid.ColumnDefinitions>
               <win:ColumnDefinition x:Name="PART_LeftPaddingColumn" Width="0" />
               <win:ColumnDefinition x:Name="PART_ButtonsHolderColumn" Width="Auto" />
```

**Comment by ghost1372** [comment]
Tnx Again,
I have applied your changes to the code.
also I must mention that the codes used to customize the title bar in WASDK v1.4 are obsolete and new API have been provided. And in the future, we are going to use new API, but until then, we are using the old api.
Also, if you're interested, here's another bug😅. If you use windows Snap Layout, drag region will not work!

and It would be great if you could send your changes via pull request

(gif is a little heavy, wait for it)
![000000555555](https://github.com/CommunityToolkit/Labs-Windows/assets/9213496/6d50335f-9e78-4c34-9a3d-3e9ebac3d590)

**Comment by dzhukovsky** [comment]
> Tnx Again, I have applied your changes to the code. also I must mention that the codes used to customize the title bar in WASDK v1.4 are obsolete and new API have been provided. And in the future, we are going to use new API, but until then, we are using the old api. Also, if you're interested, here's another bug😅. If you use windows Snap Layout, drag region will not work!
> 
> and It would be great if you could send your changes via pull request
> 
> (gif is a little heavy, wait for it) ![000000555555](https://user-images.githubusercontent.com/9213496/257825677-6d50335f-9e78-4c34-9a3d-3e9ebac3d590.gif) [ ![000000555555](https://user-images.githubusercontent.com/9213496/257825677-6d50335f-9e78-4c34-9a3d-3e9ebac3d590.gif) ](https://user-images.githubusercontent.com/9213496/257825677-6d50335f-9e78-4c34-9a3d-3e9ebac3d590.gif) [ ](https://user-images.githubusercontent.com/9213496/257825677-6d50335f-9e78-4c34-9a3d-3e9ebac3d590.gif)

I can't reproduce this bug, is this problem reproduced in other applications such as Settings?

**Comment by ghost1372** [comment]
@dzhukovsky  add a Content or Footer

```
<wuc:TitleBar.Content>
    <AutoSuggestBox PlaceholderText="Search"
                    QueryIcon="Find" />
</wuc:TitleBar.Content>
```

**Comment by dzhukovsky** [comment]
I still can't reproduce it(
can you download this app and check it for yourself? and if the bug is not reproduced, can you send me a link to your sample app so I can look?

https://drive.google.com/file/d/1mNQk4t3IRvxmRJVIkeyAPyX3Msst8joH/view?usp=drive_link

![Recording 2023-11-05 at 12 53 19](https://github.com/WinUICommunity/WinUICommunity/assets/136100876/cc8195f1-5242-4cca-b7a2-fa3c7cf8d0e3)

**Comment by ghost1372** [comment]
@dzhukovsky  Thanks for the example, but it didn't work either.
I checked a little and it seems that the reason is the scale!
I'm using a scale of 125% and that's why it doesn't work. Changing the scale to 100% solves the issue.
In any case, this issue should be solved and work the same on different scales.
Can you confirm that you also have issues with changing scale to 125%?
![Screenshot 2023-11-05 164135](https://github.com/WinUICommunity/WinUICommunity/assets/9213496/47637461-ad00-42c1-9b0a-a0c118dbe41c)

**Comment by dzhukovsky** [comment]
@ghost1372 
yes, the problem is definitely in the scale, the black lines that are responsible for the dragging regions were not drawn correctly
![image](https://github.com/WinUICommunity/WinUICommunity/assets/136100876/ccad25f9-eda5-49c6-a035-c2515017f2bd)

**Comment by dzhukovsky** [comment]
I tried to fix it but so far nothing has worked for me.
The problem is probably related to the calculation of the ActualWidth property.
I converted the TitleBar into a UserControl and the problem went away, but the visual effects disappeared(

**Comment by ghost1372** [comment]
@dzhukovsky Thank you for your effort, I take a look whenever I have a chance

**Comment by dzhukovsky** [comment]
@ghost1372 
Could you please publish 3bc38a5 to NuGet?

**Comment by ghost1372** [comment]
> @ghost1372 Could you please publish [3bc38a5](https://github.com/WinUICommunity/WinUICommunity/commit/3bc38a59170a70221cf4ceb63d6b86f78b6c9486) to NuGet?

i will upload it today

**Comment by ghost1372** [comment]
@dzhukovsky i fixed issue😅
can you test and confirm it?
[Changes-On-4ff466.patch](https://github.com/WinUICommunity/WinUICommunity/files/13265168/Changes-On-4ff466.patch)

**Comment by dzhukovsky** [comment]
@ghost1372 
cool, it works) looks great)
![Recording 2023-11-06 at 20 01 45](https://github.com/WinUICommunity/WinUICommunity/assets/136100876/345722d1-a213-4c46-99c1-3649ad74e8e7)

**Comment by dzhukovsky** [comment]
I found a new, more simple and reliable way to calculate draggable rects, I'll share the changes later.
Also, probably need to think about optimization and remove unnecessary event handlers (like TitleBar_SizeChanged because we have Window_SizeChanged) so that draggable rects are not calculated several times

**Comment by ghost1372** [comment]
> I found a new, more simple and reliable way to calculate draggable rects, I'll share the changes later. Also, probably need to think about optimization and remove unnecessary event handlers (like TitleBar_SizeChanged because we have Window_SizeChanged) so that draggable rects are not calculated several times

Great!
